spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
infrastructure:
  yandex:
    speech-kit:
      host: stt.api.cloud.yandex.net
      port: 443
      api-key: ${YANDEX_API}
  telegram:
    bot:
      api-key: ${TELEGRAM_API}
      name: VoiceGPT BOT
